### ISSUE TITLE
Maybe some sort of threading?

### ISSUE THREAD

**Issue by Anonymous3-a** [bewuethr/bash-raytracer#15]
I don't know how threading works, as I need to restart Firefox because of an update, but I'll see if I could figure this out and submit a pull request.

**Comment by Anonymous3-a** [comment]
Looked into it, I have no idea how the code works, but I can say this: add an option for how many threads, then assign fractions of the render to different commands, all using the "&" at the end.

**Comment by bewuethr** [comment]
That's been a plan for a while, and captured in #4.

I should probably point out that I'm not planning to accept contributions to this repo; it's open source, but not open contribution, simply because I want it to be entirely my creation.

You're of course free to fork the repository if you want to make changes, though.

**Comment by Anonymous3-a** [comment]
Ok
